import type { NextPage } from "next";
import Head from "next/head";
import { useState, ReactNode } from "react";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

type Props = {
	children: ReactNode;
	title: string;
};

const Layout: NextPage<Props> = ({ children, title }) => {
	const [active, setActive] = useState(false);

	const open = () => {
		setActive(!active);
	};

	return (
		<div>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Nav />
			<main>{children}</main>
			<Footer />
		</div>
	);
};

export default Layout;
